name: counter_x
description: "A new Flutter project."

# The following line prevents the package from being accidentally published to pub.dev.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# Version and build number for your application.
version: 1.0.0+1

environment:
  sdk: ^3.5.3

# Dependencies specify other packages that your package needs in order to work.
dependencies:
  flutter:
    sdk: flutter

  # Cupertino Icons for iOS style icons
  cupertino_icons: ^1.0.8
  sizer: ^3.0.4
  google_fonts: ^6.2.1
  file_picker: ^9.0.2
  http: ^1.3.0
  flutter_bloc: ^9.1.0
  shimmer: ^3.0.0
  equatable: ^2.0.7
  flutter_launcher_icons: ^0.14.3
  intl: ^0.20.2
  lottie: ^3.3.1
  firebase_auth: ^5.5.1
  firebase_core: ^3.12.1
  firebase_storage: ^12.4.4
  page_transition: ^2.2.1
  flutter_dotenv: ^5.2.1
  fluttertoast: ^8.2.12
  hive_flutter: ^1.1.0
  hive: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1
  build_runner: ^2.4.15

  # Recommended lints for good coding practices
  flutter_lints: ^4.0.0

flutter:
  # Ensures Material Icons font is included
  uses-material-design: true

  assets:
    - assets/  
    

# Configuration for Flutter Launcher Icons
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/logo.jpg"
