// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCj5Ud_3OZpRft5UYis43NT_1aNNXaL5K4',
    appId: '1:803749545768:web:2d19c915650864c47f721d',
    messagingSenderId: '803749545768',
    projectId: 'authex-72165',
    authDomain: 'authex-72165.firebaseapp.com',
    storageBucket: 'authex-72165.firebasestorage.app',
    measurementId: 'G-MTT019K33W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDB81xvdD45hJfkrJvqVeRhMjiv8xdXIGc',
    appId: '1:803749545768:android:7d511e18b5be94d47f721d',
    messagingSenderId: '803749545768',
    projectId: 'authex-72165',
    storageBucket: 'authex-72165.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCMzow5brQdP1356g2ybCMgZVJ402kKqQQ',
    appId: '1:803749545768:ios:f8b8299aa68bb2977f721d',
    messagingSenderId: '803749545768',
    projectId: 'authex-72165',
    storageBucket: 'authex-72165.firebasestorage.app',
    iosBundleId: 'com.example.counterx',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCMzow5brQdP1356g2ybCMgZVJ402kKqQQ',
    appId: '1:803749545768:ios:f8b8299aa68bb2977f721d',
    messagingSenderId: '803749545768',
    projectId: 'authex-72165',
    storageBucket: 'authex-72165.firebasestorage.app',
    iosBundleId: 'com.example.counterx',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCj5Ud_3OZpRft5UYis43NT_1aNNXaL5K4',
    appId: '1:803749545768:web:a2fba944036285707f721d',
    messagingSenderId: '803749545768',
    projectId: 'authex-72165',
    authDomain: 'authex-72165.firebaseapp.com',
    storageBucket: 'authex-72165.firebasestorage.app',
    measurementId: 'G-451H4HLRG1',
  );
}
